sudo: enabled
language: python
python:
    - "2.7"

cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - sudo chmod +x pio.sh
    - sudo ./pio.sh
